image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - test
  - build

job 1:
  stage: test
  script: node_modules/.bin/yarn test

job 2:
  stage: test
  script: node_modules/.bin/yarn e2e

release_job:
  stage: build
  script: node_modules/.bin/ng build --prod --aot
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - tags
